package com.kutztown.projectmanagement.data;


import java.util.ArrayList;

/**
 * @author Steven Gantz
 * @date 2/11/2016
 * <p/>
 * This object will contain everything required to have a full
 * entry in the progress table. Each resource can be accessed, and
 * it can be transformed into a get string to be passed to
 * the web service.
 */
public class ProgressTableEntry implements TableEntry {

    // List of all attributes within the database
    // These attributes are private and don't appear in the javadoc
    private int progressId;
    private String user;
    private String project;
    private String task;
    private String allTaskProgress;

    /**
     * Primary constructor, initialize every value in the object
     *
     */
    public ProgressTableEntry(String user, String project, String task, String allTaskProgress) {
        this.progressId = -1;
        this.user = user;
        this.project = project;
        this.task = task;
        this.allTaskProgress = allTaskProgress;
    }

    /**
     * Secondary constructor, takes an arraylist of each element in an entry and builds the object.
     *
     * @param progressTableEntry - the arraylist of entries
     **/
    public ProgressTableEntry(ArrayList<String> progressTableEntry) {

        // Raise an exception if the array does not contain all of the required values
        if (progressTableEntry.size() != 5) {
            throw new RuntimeException();
        }

        // The arraylist should have all of the entries in the order that they are in the table.
        this.progressId = Integer.parseInt(progressTableEntry.get(0));
        this.user = progressTableEntry.get(1);
        this.project = progressTableEntry.get(2);
        this.task = progressTableEntry.get(3);
        this.allTaskProgress = progressTableEntry.get(4);
    }

    /**
     * Empty constructor for construction purposes
     */
    public ProgressTableEntry(){

    }


    /**
     * returns a string that can be added to a URL for a get request.
     * Note. progressId is never sent to the database as it is generated by db.
     *
     * @return completed string that can be used for a get request
     */
    @Override
    public String writeAsGet() {
        return "user=" + this.user +
                "&project=" + this.project +
                "&task=" + this.task +
                "&allTaskProgress=" + this.allTaskProgress;
    }

    @Override
    public String writeAsValueString() {
        return null;
    }

    @Override
    public String getColumnString() {
        return null;
    }

    // Getters and setters for each method for ease of use and manipulation
    public int getProgressId() {
        return progressId;
    }

    public void setProgressId(int progressId) {
        this.progressId = progressId;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getProject() {
        return project;
    }

    public void setProject(String project) {
        this.project = project;
    }

    public String getTask() {
        return task;
    }

    public void setTask(String task) {
        this.task = task;
    }

    public String getAllTaskProgress() {
        return allTaskProgress;
    }

    public void setAllTaskProgress(String allTaskProgress) {
        this.allTaskProgress = allTaskProgress;
    }
}
